[build]
default-target = "x86_64-unknown-linux-gnu"

[target.arm64-unknown-linux-gnu]
image = "ghcr.io/thinkier/bt-adv-aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/thinkier/bt-adv-x86_64-unknown-linux-gnu"
